version: "3.9"

services:
  backend:
    build: ./server
    container_name: myclinic-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - ./.env
    environment:
      MONGODB_URI: mongodb+srv://myclinicuser:welcome!23@myclinic-cluster.ht5hi.mongodb.net/?retryWrites=true&w=majority&appName=myclinic-cluster

  mongodb:
    image: mongo:8
    container_name: myclinic-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: