// // ... existing imports ...
// const doctorDispensaryRoutes = require('./routes/doctorDispensaryRoutes');

// // ... other middleware and route setup ...

// // Register routes
// app.use('/api/doctor-dispensaries', doctorDispensaryRoutes);

// // ... rest of the file ...